### ISSUE TITLE
Docker-compose Error 400 Bad request

### ISSUE THREAD

**Issue by MaximeZumstein** [tryvin/figma-linux-font-helper#5] opened 2020-02-26 10:59 UTC
Hi,

I just tested to use your font-helper with Ubuntu and Docker, unfortunately I got those errors when I went to figma.com > settings account :
`server_1  |  * Serving Flask app "server" (lazy loading)
server_1  |  * Environment: production
server_1  |    WARNING: Do not use the development server in a production environment.
server_1  |    Use a production WSGI server instead.
server_1  |  * Debug mode: off
server_1  |  * Running on http://0.0.0.0:7335/ (Press CTRL+C to quit)
server_1  | 172.18.0.1 - - [26/Feb/2020 10:54:53] code 400, message Bad request version ('\x9f\x8b\x90û±¬Áô´6i\x00"\x9a\x9a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
server_1  | 172.18.0.1 - - [26/Feb/2020 10:54:53] "üeîoTãýÞ-¡çm?1«>·ÓÖmr4zÚ üZÄ3eiýy³J	/5" HTTPStatus.BAD_REQUEST -
server_1  | 172.18.0.1 - - [26/Feb/2020 10:54:55] code 400, message Bad request version ('¬Ý\x00"**\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
server_1  | 172.18.0.1 - - [26/Feb/2020 10:54:55] "ü4ùU³+þë{;Ê\]^ì±:ÿ^îÅ¥ÛÃ@P²² A¢S£°£Y|Iyb#w^6LbûKX ¬Ý"**À+À/À,À0Ì©Ì¨ÀÀ/5" HTTPStatus.BAD_REQUEST -
^[[?62;c^[[?62;cserver_1  | 172.18.0.1 - - [26/Feb/2020 10:54:57] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03F¬?\x97pSegÀôêÒìÌËU\x13ù\x05\x03\x12\x90H'Ñ¼Ë!\x8aù_\x03")
server_1  | 172.18.0.1 - - [26/Feb/2020 10:54:57] "üF¬?pSegÀôêÒìÌËUù/5" HTTPStatus.BAD_REQUEST -
server_1  | 172.18.0.1 - - [26/Feb/2020 10:54:59] code 400, message Bad request version ('ÞÒÜ\x95\x80G´Òo×\x98ÖL\x8f\x02÷\x00"ÚÚ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
`

**Comment by tryvin** [comment] 2022-04-17 13:44
Closing this as I can't reproduce.

**Closed as completed by tryvin** 2022-04-17 13:44 UTC
